---
title: 夏沐尧的博客
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:year-:month-:day-:title/"
paginate: 10
markdown: kramdown
encoding: utf-8
author:
  name: 夏沐尧
  email: XiaMuYaodqx@gmail.com
  link: https://xiamuyao.github.io
  weibo: https://weibo.com/liqing215
  github: https://github.com/xiamuyao
  zhihu: https://www.zhihu.com/people/xia-mu-yao-13/activities
  juejin: https://juejin.im/user/58f24aa961ff4b0058f13f65
  stackoverflow: https://stackoverflow.com/users/5871340/jimmylv
description: 崇尚技术,不局限于技术。
url: https://xiamuyao.github.io
repo: https://github.com/XiaMuYao/XiaMuYao.github.io
rss: "/pages/atom.xml"
gavatar: "/public/img/gavatar.jpg"
favicon: "/public/img/favicon.ico"
ga:
  id: UA-74789926-1
  url: https://xiamuyao.github.io
disqus:
  shortname: xiamuyao-github-io
active: 编程
cates:
- React
- PKM
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  search: 搜索
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll/tagging
- jekyll-tagging-related_posts
- jekyll-seo-tag
- jekyll-mermaid
exclude:
- ".idea/"
- ".github/"
- ".travis/"
- node_modules/
- themes/
- _posts/演讲/assets
